### ISSUE TITLE
issue during installation

### ISSUE THREAD

**Issue by bastienEichenberger** [nicoespeon/trello-kanban-analysis-tool#20]
Hi,

Thank you very much for you Tool. It's exactly what I'm looking for.
I have an issue during the installation:

npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'cycle/core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'tkat'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 14.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Applications/MAMP/htdocs/trello-kanban-analysis-tool
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Applications/MAMP/htdocs/trello-kanban-analysis-tool/npm-debug.log
npm ERR! not ok code 0

Do you have any Idea how to fix this?
Thank you very much.

**Comment by nicoespeon** [comment]
Hi @bastienEichenberger!

This remind me https://github.com/cyclejs/core/issues/152.

Cycle.js use [scoped packages](https://docs.npmjs.com/getting-started/scoped-packages) to namespace it. But it requires a recent version of npm (v2.7 or higher I think).

You could check your current npm version with `npm --version` and upgrade it with `[sudo] npm install npm@latest -g` (the current stable version of npm is 3.9.3).

Let me know if that resolves your problem 😃

**Comment by bastienEichenberger** [comment]
Hi @nicoespeon ,

Thank you very much for your Answer! It works now :)
Just the User Interface is a bit different.

![capture d ecran 2016-05-29 a 09 48 54](https://cloud.githubusercontent.com/assets/3861972/15631965/06d17a86-2583-11e6-8696-e3f1136643f6.png)

**Comment by nicoespeon** [comment]
Actually, that's strange.

Try to pull the latest version of the repo (in case you're not up-to-date).

If it's still ugly, could you open your console and tell me if some errors have pop up? 😃

**Comment by bastienEichenberger** [comment]
Hi,
Thank you again for your Help!
The repo is up to date … I just cloned the repository and I have the following warning during installation:
├── @cycle/core@6.0.3 
└── UNMET PEER DEPENDENCY d3@^3.4.4

npm WARN nvd3@1.8.2 requires a peer of d3@^3.4.4 but none was installed.

**Comment by nicoespeon** [comment]
This is true, I'll have a look at it.

However, [I included d3.js right into index.html](https://github.com/nicoespeon/trello-kanban-analysis-tool/blob/master/app/assets/index.html#L15) so this shouldn't be an issue.

This mostly looks like an issue with CSS (buttons not spread horizontally, chart not at correct height).

This is what you should see:

<img width="1227" alt="capture d ecran 2016-05-31 a 19 14 41" src="https://cloud.githubusercontent.com/assets/1094774/15683896/f4b322d0-2764-11e6-92ee-971a41818876.png">
<img width="981" alt="capture d ecran 2016-05-31 a 19 22 18" src="https://cloud.githubusercontent.com/assets/1094774/15683897/f4bc8f6e-2764-11e6-8dcc-15e280d6ea9e.png">

**Comment by bastienEichenberger** [comment]
Hello,
I just reinstall you Apps and it works great now!
So you can close the issue :)

I just figure it out something, when I click on the button _Get Actions_ nothing appear?
I don't know how does this button works?

Have a good day.

**Comment by nicoespeon** [comment]
The *Get Actions* button is here to fetch data from Trello. It is useful to refresh data after a while without refreshing the page, but I also realized that the wording is not clear.

I'll edit for a clearer label like *Refresh data*. Thanks for pointing out!
