### ISSUE TITLE
add other metrics

### ISSUE THREAD

**Issue by bastienEichenberger** [nicoespeon/trello-kanban-analysis-tool#27]
Hi,

It could be a good Idea to add more metrics such as WIP in the Kaban Analysis Tool.

For example I have 5 Columns (To do, Sprint Planning, Doing, Waiting, Done).
Directly on the Graph it could be great to have a way to calculate the work in progress.
In my example the work in progress is the sum of 2 columns (Doing, Waiting).

Best regards!
Bastien

**Comment by nicoespeon** [comment]
Hi @bastienEichenberger and thanks for suggesting new features =)

Concerning WIP, for now you can hover any point of the graph to display detailed values:

![image](https://cloud.githubusercontent.com/assets/1094774/15812855/fa045ea8-2bb9-11e6-95ce-26579f757884.png)

If I correctly understand, what you'd like is to indicate which columns are considered as *Work in progress* ones and to display the # of cards (= WIP) in these. I'm I correct?

If so, I'm wondering if the CFD doesn't already give you that information at a glance (visual evolution of WIP through days)?

**Comment by bastienEichenberger** [comment]
Hi @nicoespeon,
Thanks for your response. Yes it's enough to get the WIP on the Chart.
I'm just thinking about which Metrics we need in our Company:
- It could be great to be able to make an Aggregation of many Boards datas. For example I would like to know how many WIP I have in a list of Boards. If thoses boards have the same lists (Todo Doing, Done)…
- An other missing Tool in Trello is a Way to make a Chart with Members WIP. For example, if I would like to know which Member has how many assigned Cards.

**Comment by bastienEichenberger** [comment]
This Tools could be an example:
https://getcorrello.com/

**Comment by nicoespeon** [comment]
Yep, Corrello is a great tool indeed 👍 

Another (free) tool that exists and might be helpful to you is [Ollert](https://ollertapp.com/boards). The point of TKAT was to focus on Kanban metrics while tools like Ollert where giving me Agile metrics in general − most of them I don't use, still missing Cycle Times / Lead Times though. Plus, it was also a concrete use case to practice FRP with Cycle.js.

Back to your points:

- Concerning the aggregation of multiple boards, I think it would be too specific 😕 
Boards would need to have the same lists for this to work. Furthermore, when you are doing Kanban, you usually use 1 board to represent a specific flow for a specific team. If you have multiple boards with the same flow, implying the same team, then it might raise the question: shouldn't you merge those boards.

- Concerning the WIP per member, this is something you can have very quickly on Trello using filter on someone's head. 
It doesn't sound related to Kanban metrics to me, which is what this tool is meant to focus on − you couldn't have the historical CFD, Lead Time, Cycle Times or Throughput just with Trello. However, I'm up to enlarge TKAT features to make it useful for the most. Just I'd like to keep it focus on one job to do it well 😃

Waiting for your feedback on these points.

**Comment by nicoespeon** [comment]
FYI: I'm closing this issue but it's still up to discussion 😉
