### ISSUE TITLE
Selected lists mess up when you select another board

### ISSUE THREAD

**Issue by bastienEichenberger** [nicoespeon/trello-kanban-analysis-tool#31]
Hi,
I just saw a little bug.
When I change the active Board I have the same list on _Work begin_and _Work end_.
If I clich on _Work end_ the data aren't loaded. 
When I click on the button refresh data I don't obtain new datas.

![capture d ecran 2016-06-07 a 09 15 39](https://cloud.githubusercontent.com/assets/3861972/15849084/f9c495a2-2c90-11e6-8fdd-3cb1a69d681f.png)
![capture d ecran 2016-06-07 a 09 15 46](https://cloud.githubusercontent.com/assets/3861972/15849085/f9c66e2c-2c90-11e6-912b-b6e705fb3e60.png)

**Comment by nicoespeon** [comment]
Thanks for pointing out @bastienEichenberger!

The fact that the last list isn't correctly selected when you change the selected board is a behavior I want to improve indeed. I edited your issue to deal with that little bug in UX.

Concerning the fact that data doesn't update after you select the appropriate list, I noticed this to be a regression from #30. I’ll find out why and solve this issue in this PR. I’ll let you know when I'm done =)

Thanks for catching those!

**Comment by nicoespeon** [comment]
Well I concluded wrong and it's not related at all to #28 / #30.

This is an actual bug: something is not getting properly updated when a new board is selected. It stays on locally stored values of selected lists, which may not match the new board ones, hence this behavior.

**Comment by nicoespeon** [comment]
Use case
---

Change selected board.

- Expected: first & last lists of the board are the limits
- Actual: 
    - if a list has the same name, it is selected
    - otherwise, first list is selected, even for the *"Work ends"* select
    - data display the last list only

It seems to mess up with localStorage values.
