### ISSUE TITLE
bug with chart panel

### ISSUE THREAD

**Issue by bastienEichenberger** [nicoespeon/trello-kanban-analysis-tool#32]
Hi,

I have a strange behavior when I click on the Chart Panel.
![bug](https://cloud.githubusercontent.com/assets/3861972/15900750/e7860612-2da0-11e6-9ef6-1c3d8840be10.png)

**Comment by nicoespeon** [comment]
Yep I noticed that too. Thanks for reporting 👍

**Comment by nicoespeon** [comment]
Note for later: fade out details on mouseout from the graph. It should solve this issue.
